### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by vanillamasonry** [geocine/sphinx-se-builds-windows#1]
Hello,

I am wondering if you can Build the plugin ha_sphinx.dll for the actual mysql 5.6.23 and Sphinx 2.2.7 or how can I build myself - configurations and the compiler that you are using.

Thank you in advance,
Paul

**Comment by geocine** [comment]
I have pushed new builds: mysql 5.6.23 and sphinxse 2.2.7 x86 and x64 for windows . you are welcome - Aivan
