### ISSUE TITLE
We prefer the mainstream version of the Sphinx that all PHP+MYSQL se!

### ISSUE THREAD

**Issue by letwang** [geocine/sphinx-se-builds-windows#4]
We prefer the mainstream version of the Sphinx that all PHP+MYSQL se
I compiled the latest version on Ubuntu, always without success; Windos but do not know how to compile, were too upset!
There is an urgent need:
windos64:PHP7.0.10+MySQL Community Server 5.7.14
ubuntu64:PHP version: 5.6.21-1+donate.sury.org~precise+4 + Server version: 5.6.31-0ubuntu0.14.04.2 - (Ubuntu)

If you can spare the time risk, na thank you!

**Comment by geocine** [comment]
I will look into this later once I get home

**Comment by letwang** [comment]
Sphinx 2.2.11-release

**Comment by geocine** [comment]
I only compile binaries for windows so if you try to use this on linux it will not work . also php has nothing to do with this

**Comment by letwang** [comment]
Grateful!
Appreciate it!

**Comment by geocine** [comment]
Hi @letwang sorry for the delay. I am also having issues compiling the latest builds on windows so looking for solutions.

**Comment by geocine** [comment]
@letwang  Hi sorry it took some time here it is. https://github.com/geocine/sphinx-se-builds-windows/tree/master/mysql-5.7.15-sphinx-2.2.11
